/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#7ff3be",
        "inverse-primary": "#618bff",
        "primary-dim": "#0048c1",
        "inverse-surface": "#0b0f10",
        "primary": "#0053db",
        "surface-container": "#e8eff3",
        "on-tertiary-container": "#005a3d",
        "primary-container": "#dbe1ff",
        "on-primary-container": "#0048bf",
        "tertiary-dim": "#005f41",
        "tertiary": "#006d4b",
        "secondary": "#506076",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#006545",
        "primary-fixed": "#dbe1ff",
        "on-error-container": "#752121",
        "surface-bright": "#f7f9fb",
        "secondary-fixed": "#d3e4fe",
        "on-primary-fixed-variant": "#0050d4",
        "on-secondary-container": "#435368",
        "secondary-fixed-dim": "#c5d6f0",
        "outline": "#717c82",
        "outline-variant": "#a9b4b9",
        "surface-container-low": "#f0f4f7",
        "error": "#9f403d",
        "error-container": "#fe8983",
        "on-background": "#2a3439",
        "tertiary-container": "#7ff3be",
        "inverse-on-surface": "#9a9d9f",
        "surface-container-highest": "#d9e4ea",
        "surface-variant": "#d9e4ea",
        "surface-container-high": "#e1e9ee",
        "on-error": "#fff7f6",
        "on-secondary": "#f7f9ff",
        "on-tertiary-fixed": "#00452e",
        "on-primary": "#f8f7ff",
        "on-surface-variant": "#566166",
        "background": "#f7f9fb",
        "surface": "#f7f9fb",
        "surface-dim": "#cfdce3",
        "on-tertiary": "#e6ffef",
        "on-surface": "#2a3439",
        "tertiary-fixed-dim": "#71e4b1",
        "on-secondary-fixed": "#314055",
        "primary-fixed-dim": "#c7d3ff",
        "surface-tint": "#0053db",
        "on-primary-fixed": "#003798",
        "secondary-dim": "#44546a",
        "on-secondary-fixed-variant": "#4d5d73",
        "error-dim": "#4e0309",
        "secondary-container": "#d3e4fe"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"],
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
